# Generated by Django 5.1 on 2024-08-22 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product-images/')),
                ('rating', models.CharField(max_length=50)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prodects.category')),
            ],
        ),
    ]
